const crypto = require('node:crypto');
const fs = require('node:fs');
const path = require('node:path');

const root = path.resolve(__dirname, '..');
const envPath = path.join(root, '.env');
const outputPath = path.join(root, 'data', 'demo-auth.js');
const iterations = 600000;

if (!fs.existsSync(envPath)) {
    console.error('Missing .env. Add DEMO_PASSWORD locally, then run this generator again.');
    process.exit(1);
}

const passwordLine = fs.readFileSync(envPath, 'utf8').split(/\r?\n/)
    .find((line) => /^\s*DEMO_PASSWORD\s*=/.test(line));
if (!passwordLine) {
    console.error('Missing DEMO_PASSWORD in .env.');
    process.exit(1);
}

let password = passwordLine.slice(passwordLine.indexOf('=') + 1).trim();
if ((password.startsWith('"') && password.endsWith('"')) || (password.startsWith("'") && password.endsWith("'"))) {
    password = password.slice(1, -1);
} else {
    password = password.replace(/\s+#.*$/, '').trim();
}
if (!password) {
    console.error('DEMO_PASSWORD is empty in .env.');
    process.exit(1);
}

const salt = crypto.randomBytes(16);
const digest = crypto.pbkdf2Sync(password, salt, iterations, 32, 'sha256');
const verifier = [
    '// Generated by scripts/generate_demo_auth.js. Do not put the password in this file.',
    'window.DEMO_PASSWORD_VERIFIER = Object.freeze({',
    `    salt: '${salt.toString('hex')}',`,
    `    hash: '${digest.toString('hex')}',`,
    `    iterations: ${iterations},`,
    "    algorithm: 'SHA-256'",
    '});',
    ''
].join('\n');

fs.writeFileSync(outputPath, verifier, { encoding: 'utf8', mode: 0o644 });
console.log('Generated data/demo-auth.js from .env. The password itself was not written to the output.');
